CivBudget/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('budget.urls', namespace="budget")),
    url(r'^admin/', admin.site.urls),
]

budget/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add_booking$', views.add_booking, name='add_booking'),
    url(r'^add_rate', views.add_rate, name='add_rate'),
    url(r'^delete_booking/(?P<booking_id>[0-9]+)/$', views.delete_booking, name='delete_booking'),
    url(r'^delete_rate/(?P<rate_id>[0-9]+)/$', views.delete_rate, name='delete_rate'),
    url(r'^login$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
]

budget/models.py
from django.db import models
from django import forms
from django.forms import ModelForm
from django.forms import Form
from django.contrib.auth.models import User

# Create your models here.

class Booking(models.Model):
    date = models.DateTimeField()
    value = models.DecimalField(max_digits=10, decimal_places=2)
    name = models.CharField(max_length=100)
    user = models.ForeignKey(User)

    def __str__(self):
        return self.name


class Rate(models.Model):
    days = models.IntegerField()
    value = models.DecimalField(max_digits=10, decimal_places=2)
    daily_value = models.DecimalField(max_digits=10, decimal_places=2)
    name = models.CharField(max_length=100)
    user = models.ForeignKey(User)

    def __str__(self):
        return self.name

    def calculate_daily_value(self):
        self.daily_value = self.value / self.days

# TODO Migration!
class BookingTotal(models.Model):
    type = models.IntegerField()
    value = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateTimeField
    user = models.ForeignKey(User)


class BookingForm(Form):
    date = forms.DateTimeField(input_formats=['%d.%m.%Y'])
    value = forms.DecimalField()
    name = forms.CharField()


class RateForm(ModelForm):
    class Meta:
        model = Rate
        fields = ['days', 'value', 'name']

budget/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required

from dateutil import parser
from .models import *
from .utils import Utils
from django.utils import timezone
import datetime
from datetime import timedelta
from django.db.models import Sum
from graphos.sources.model import SimpleDataSource
from graphos.renderers.morris import BarChart
from collections import Counter


def daterange(start_date, end_date):
    for n in range(int((end_date - start_date).days)):
        yield start_date + timedelta(n)

# TODO add BookingTotals-functonality and remove old stuff
@login_required
def index(request):
    user = request.user
    now = timezone.now()
    today = now.replace(hour=0, minute=0, second=0, microsecond=0)
    first_day_of_month = today.replace(day=1)
    monday_of_this_week = today - timedelta(days=today.weekday())
    rate_list = Rate.objects.filter(user=user).order_by('daily_value')
    # TODO refactor this mess!
    bookings_of_day = Booking.objects.filter(user=user).order_by('value').filter(date__range=[today, now])
    bookings_of_week = Booking.objects.filter(user=user).order_by('value').filter(
         date__range=[monday_of_this_week, now]).aggregate(balance_of_week=Sum('value'))
    bookings_of_month = Booking.objects.filter(user=user).order_by('value').filter(
        date__range=[first_day_of_month, now]).aggregate(balance_of_month=Sum('value'))
    bookings_forever =  Booking.objects.filter(user=user).aggregate(balance_forever=Sum('value'))
    bookings = Booking.objects.filter(user=user).order_by('date')
    start_date = bookings[0].date
    end_date = today
    #aggregated_by_day = [['Date', 'Value']]
    #for single_date in daterange(start_date, end_date):
    #    bookings_up_to_day = Booking.objects.filter(user=user).filter(
    #        date__range=[start_date, single_date]).aggregate(
    #        balance_up_to_day=Sum('value'))['balance_up_to_day']
    #    aggregated_by_day.append([single_date, bookings_up_to_day])
    #data_source = SimpleDataSource(aggregated_by_day)
    #chart = BarChart(data_source)
    context = {
        'bookings_of_day': bookings_of_day,
        'rate_list': rate_list,
        'magic_number': Utils.calculate_daily_rate(rate_list),
        'booking_total': Utils.calculate_total(bookings_of_day),
        'today': timezone.now(),
        'balance_of_week': bookings_of_week['balance_of_week'],
        'balance_of_month': bookings_of_month['balance_of_month'],
        'balance_forever': bookings_forever['balance_forever'],
     #   'chart': chart,

    }
    return render(request, 'budget/index.html', context)


@login_required
def add_booking(request):
    if request.method == 'POST':
        form = BookingForm(request.POST)
        if form.is_valid():
            booking = Booking(name=form.cleaned_data['name'], value=form.cleaned_data['value'],
                              date=form.cleaned_data['date'], user=request.user)
            booking.save()
    return redirect('/')


@login_required
def add_rate(request):
    if request.method == 'POST':
        form = RateForm(request.POST)
        if form.is_valid():
            rate = Rate(name=form.cleaned_data['name'], value=form.cleaned_data['value'],
                        days=form.cleaned_data['days'], user=request.user)
            rate.calculate_daily_value()
            rate.save()
    return redirect('/')


@login_required
def delete_booking(request, booking_id):
    booking = Booking.objects.get(id=booking_id)
    booking.delete()
    return redirect('/')


@login_required
def delete_rate(request, rate_id):
    rate = Rate.objects.get(id=rate_id)
    rate.delete()
    return redirect('/')

budget/templates/budget/index.html
<html>
{% load staticfiles %}
{% load bootstrap3 %}

<head>
    <title>CivBudget</title>

    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>

    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js"></script>
    <script src="//cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/src/js/bootstrap-datetimepicker.js"></script>
    <link href="//cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/build/css/bootstrap-datetimepicker.css"
          rel="stylesheet">
    <link rel="icon" sizes="64x64" href="{% static '/ico/civ_budget_favicon_64x64.ico'%}">
    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>

<body>
<div class="page-header">
    <div class="container">
        <div class="row">
            <h1>
                <div class="col-xs-11">Civ inspired Budget
                    <small>Daily turns for a better overview</small>
                </div>
                <div class="col-xs-1">
                    <div class="dropdown">
                        <button class="btn btn-default" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                    <span class="glyphicon glyphicon-menu-hamburger"
                          aria-hidden="true"></span>
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dLabel">
                            <li>
                                <a data-toggle="modal" data-target="#modal-logout"> Log Out </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </h1>
        </div>
    </div>
</div>


<div class="modal fade" id="modal-logout" tabindex="-1" role="dialog" aria-labelledby="Log Out">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modal-logout-label">Log Out</h4>
            </div>
            <div class="modal-body">
                Do you want to Log Out?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <a class="btn btn-danger" href="{% url 'budget:logout' %}">Log Out</a>
            </div>
        </div>
    </div>
</div>

<div class="container">

    <div class="table-responsive" style="overflow: visible">
        <table class="table table-bordered table-striped">
            <thead>
            <th>Booking</th>
            <th>Date</th>
            <th>Value (Total: {{ booking_total }}€)</th>
            <th></th>
            </thead>
            {% for booking in bookings_of_day %}
                {% if booking.value < 0 %}
                    <tr class="danger">
                        {% else %}
                    <tr class="success">
                {% endif %}
            <td>{{ booking.name }}</td>
            <td>{{ booking.date | date:"d.m.Y" }}</td>
            <td>{{ booking.value }}€</td>
            <td>
                <a href="{% url 'budget:delete_booking' booking.id %}" class="btn btn-danger">
                                    <span class="glyphicon glyphicon-trash"
                                          aria-hidden="true"></span>
                </a>
            </td>
            </tr>
            {% endfor %}
            <tr>
                <form class="form-inline" action="{% url 'budget:add_booking' %}" method="post">
                    {% csrf_token %}
                    <td><input name="name" type="text" class="form-control" placeholder="New Booking" required/>
                    </td>
                    <td>
                        <div>
                            <div class="form-group">
                                <div class='input-group date' id='datetimepicker1'>
                                    <input name="date" type='text' class="form-control"
                                           value="{{ today | date:"dd.mm.YYYY" }}" required/>
                                    <span class=" input-group-addon">
                                            <span class="glyphicon glyphicon-calendar"></span>
                                            </span>
                                </div>
                            </div>
                            <script type="text/javascript">
                                $(function () {
                                    $('#datetimepicker1').datetimepicker({
                                        locale: 'de',
                                        format: 'DD.MM.YYYY'
                                    });
                                });
                            </script>
                        </div>
                    </td>
                    <td>
                        <div class="input-group">
                            <input name="value" type="number" class="form-control" placeholder="Value" step="0.01"
                                   required/>
                            <div class="input-group-addon">€</div>
                        </div>
                    </td>
                    <td>
                        <button type="submit" class="btn btn-primary">
                                    <span class="glyphicon glyphicon-plus"
                                          aria-hidden="true"></span>
                        </button>
                    </td>
                </form>
            </tr>
        </table>
    </div>


    <div class="panel-group" id="accordion-rate" role="tablist" aria-multiselectable="true">

        <div class="panel panel-default">
            <a role="button" data-toggle="collapse" data-parent="#accordion"
               href="#rate-content"
               aria-expanded="false"
               aria-controls="rate-content">
                <div class="panel-heading" role="tab" id="headingOne">
                    <h4 class="panel-title"> Rates
                    </h4>
                </div>
            </a>
            <div id="rate-content" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-rate">
                <div class="table-responsive">

                    <table class="table table-bordered table-striped">
                        <thead>
                        <th>Rate</th>
                        <th>Value</th>
                        <th>Days</th>
                        <th>Daily Value (Total: {{ magic_number }}€)</th>
                        <th></th>
                        </thead>

                        {% for rate in rate_list %}
                            {% if rate.daily_value < 0 %}
                                <tr class="danger">
                                    {% else %}
                                <tr class="success">
                            {% endif %}
                        <td>{{ rate.name }}</td>
                        <td>{{ rate.value }}€</td>
                        <td>{{ rate.days }}</td>
                        <td>{{ rate.daily_value }}€</td>
                        <td>
                            <a href="{% url 'budget:delete_rate' rate.id %}" class="btn btn-danger">
                                    <span class="glyphicon glyphicon-trash"
                                          aria-hidden="true"></span>
                            </a>
                        </td>
                        </tr>
                        {% endfor %}
                        <tr>

                            <form class="form-inline" action="{% url 'budget:add_rate' %}" method="post">
                                {% csrf_token %}
                                <td><input name="name" type="text" class="form-control" placeholder="New Rate"
                                           required/>
                                </td>
                                <td>
                                    <div class="input-group">
                                        <input name="value" type="number" class="form-control" placeholder="Value"
                                               step="0.01"
                                               required/>
                                        <div class="input-group-addon">€</div>
                                    </div>
                                </td>
                                <td><input name="days" type="number" class="form-control" placeholder="Days" required/>
                                </td>
                                <td>Will be calculated</td>
                                <td>
                                    <button type="submit" class="btn btn-primary">
                                    <span class="glyphicon glyphicon-plus"
                                          aria-hidden="true"></span>
                                    </button>
                                </td>
                            </form>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>


    <div class="panel-group" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
            <div class="panel-heading" role="tab">
                Balances
            </div>

            <div class="panel panel-default" role="tabpanel" style="padding-left: 10px">
                <h4>
                    Balance of this Week: {{ balance_of_week }}€
                </h4>
                <h4>
                    Balance of this Month: {{ balance_of_month }}€
                </h4>
                <h4>
                    Balance Forever: {{ balance_forever }}
                </h4>
            </div>
        </div>
    </div>

    <div class="panel-group" id="accordion-graph" role="tablist" aria-multiselectable="true">

        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="heading-graph">
                <h4 class="panel-title"> Graphs
                </h4>
            </div>
            <div id="graph-content" class="panel-default" role="tabpanel"
                 aria-labelledby="heading-graph">
                <!--  chart.as_html -->
            </div>
        </div>
    </div>


</div>
</body>
</html>